---
Name: wkhtmltox
Before: app
---
Grasenhiller\WkHtmlToX:
  bypass_proxy_for_own_site: true
  Pdf:
    options:
      global:
        0: no-outline
        1: enable-javascript
        2: disable-smart-shrinking
        encoding: UTF-8
        dpi: 72
        image-quality: 100
        image-dpi: 72
        margin-bottom: 0
        margin-left: 0
        margin-right: 0
        margin-top : 0
      A3Portrait:
        page-size: A3
        orientation: Portrait
      A3Landscape:
        page-size: A3
        orientation: Landscape
      A4Portrait:
        page-size: A4
        orientation: Portrait
      A4Landscape:
        page-size: A4
        orientation: Landscape
      A5Portrait:
        page-size: A5
        orientation: Portrait
      A5Landscape:
        page-size: A5
        orientation: Landscape
      A6Portrait:
        page-size: A6
        orientation: Portrait
      A6Landscape:
        page-size: A6
        orientation: Landscape
  Image:
    options:
      global:
        0: transparent
        1: disable-smart-width
        format: png
        quality: 100